<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class SanPhamSeeder extends Seeder
{
    public function run()
    {
        DB::table('san_phams')->delete();
        DB::table('san_phams')->truncate();
        DB::table('san_phams')->insert([
            [
                'id_danh_muc'  => 1,
                'ten_san_pham' => 'Hồng trà latte',
                'slug_san_pham' => Str::slug('Hồng trà latte'),
                'mo_ta_ngan'    => 'là loại trà sữa được pha chế bằng cách thêm sữa tươi vào hồng trà, có vị ngọt và thơm.',
                'mo_ta_chi_tiet' => 'chứa nhiều caffeine, giúp tăng cường sự tỉnh táo và năng lượng cho người uống. Hồng Trà Latte thường được uống vào buổi sáng hoặc khi cần làm việc lâu.',
                'trang_thai' => '1',
                'gia_ban' => '40.000',
                'gia_khuyen_mai'    => '36.000',
                'hinh_anh'    => 'https://bom.so/T6zU1z',
                'so_luong'  => '20',
            ],
            [
                'id_danh_muc'  => 1,
                'ten_san_pham' => 'Matcha Latte Đậu Đỏ',
                'slug_san_pham' => Str::slug('Matcha Latte Đậu Đỏ'),
                'mo_ta_ngan'    => 'là loại trà sữa được pha chế bằng cách thêm sữa tươi và đậu đỏ vào matcha, có vị ngọt và bổ dưỡng.',
                'mo_ta_chi_tiet' => 'chứa nhiều chlorophyll, giúp thanh lọc, giải độc và làm sáng da cho người uống. Matcha Latte Đậu Đỏ thường được uống vào buổi chiều hoặc khi muốn bổ sung dinh dưỡng.',
                'trang_thai' => '1',
                'gia_ban' => '50.000',
                'gia_khuyen_mai'    => '45.000',
                'hinh_anh'    => 'https://bom.so/AENCjt',
                'so_luong'  => '20',
            ],
            [
                'id_danh_muc'  => 1,
                'ten_san_pham' => 'Tứ Kỳ Xuân Latte',
                'slug_san_pham' => Str::slug('Tứ Kỳ Xuân Latte'),
                'mo_ta_ngan'    => 'là loại trà sữa được pha chế bằng cách thêm sữa tươi vào trà tứ kỳ xuân, có vị ngọt và đậm đà.',
                'mo_ta_chi_tiet' => 'chứa nhiều tinh dầu, giúp giảm stress, thư giãn và tăng cường trí nhớ cho người uống. Tứ Kỳ Xuân Latte thường được uống vào buổi sáng hoặc khi cần tập trung.',
                'trang_thai' => '1',
                'gia_ban' => '40.000',
                'gia_khuyen_mai'    => '36.000',
                'hinh_anh'    => 'https://bom.so/Yk2bIl',
                'so_luong'  => '20',
            ],
            [
                'id_danh_muc'  => 1,
                'ten_san_pham' => 'Lục Trà Latte',
                'slug_san_pham' => Str::slug('Lục Trà Latte'),
                'mo_ta_ngan'    => 'là loại trà sữa được pha chế bằng cách thêm sữa tươi vào lục trà, có vị ngọt và mát.',
                'mo_ta_chi_tiet' => 'chứa nhiều catechin, giúp chống viêm, kháng khuẩn và ngăn ngừa ung thư cho người uống. Lục Trà Latte thường được uống vào buổi chiều hoặc khi muốn giải khát.',
                'trang_thai' => '1',
                'gia_ban' => '50.000',
                'gia_khuyen_mai'    => '45.000',
                'hinh_anh'    => 'https://bom.so/2alMpD',
                'so_luong'  => '20',
            ],
            [
                'id_danh_muc'  => 1,
                'ten_san_pham' => 'Sữa Tươi Thiên Thảo Lục Vị',
                'slug_san_pham' => Str::slug('Sữa Tươi Thiên Thảo Lục Vị'),
                'mo_ta_ngan'    => 'là loại sữa tươi được pha chế bằng cách thêm thiên thảo và lục vị vào sữa, có vị ngọt và thanh.',
                'mo_ta_chi_tiet' => 'chứa nhiều vitamin A, E và K, giúp bảo vệ mắt, da và máu cho người uống. Sữa Tươi Thiên Thảo Lục Vị thường được uống vào buổi trưa hoặc khi muốn thanh lọc cơ thể.',
                'trang_thai' => '1',
                'gia_ban' => '40.000',
                'gia_khuyen_mai'    => '36.000',
                'hinh_anh'    => 'https://bom.so/l0u9uo',
                'so_luong'  => '20',
            ],
            [
                'id_danh_muc'  => 1,
                'ten_san_pham' => 'Hồng Trà Sữa Nướng',
                'slug_san_pham' => Str::slug('Hồng Trà Sữa Nướng'),
                'mo_ta_ngan'    => 'là loại trà sữa được pha chế bằng cách thêm sữa nướng vào hồng trà, có vị ngọt và thơm.',
                'mo_ta_chi_tiet' => 'mùi hương đặc trưng của sữa nướng, tạo ra cảm giác ấm áp và ngon miệng cho người uống. Hồng Trà Sữa Nướng thường được uống vào buổi tối hoặc khi muốn ăn vặt.',
                'trang_thai' => '1',
                'gia_ban' => '45.000',
                'gia_khuyen_mai'    => '40.500',
                'hinh_anh'    => 'https://bom.so/EaG743',
                'so_luong'  => '20',
            ],
            [
                'id_danh_muc'  => 1,
                'ten_san_pham' => 'OOlong Latte Yến Mạch',
                'slug_san_pham' => Str::slug('OOlong Latte Yến Mạch'),
                'mo_ta_ngan'    => 'là loại trà sữa được pha chế bằng cách thêm sữa tươi và yến mạch vào trà ô long, có vị béo ngậy và dinh dưỡng.',
                'mo_ta_chi_tiet' => 'chứa nhiều protein, canxi và chất xơ, giúp bổ sung dinh dưỡng, tăng cường xương khớp và hỗ trợ tiêu hóa cho người uống. Ô Long Latte Yến Mạch thường được uống vào buổi sáng hoặc khi cần bổ sung năng lượng.',
                'trang_thai' => '1',
                'gia_ban' => '35.000',
                'gia_khuyen_mai'    => '31.500',
                'hinh_anh'    => 'https://bom.so/S1VD1h',
                'so_luong'  => '20',
            ],
            [
                'id_danh_muc'  => 1,
                'ten_san_pham' => 'Ô Long Chanh Leo',
                'slug_san_pham' => Str::slug('Ô Long Chanh Leo'),
                'mo_ta_ngan'    => 'là loại trà được pha chế bằng cách thêm chanh leo vào trà ô long, có vị thanh và dịu.',
                'mo_ta_chi_tiet' => 'chứa nhiều chất chống oxy hóa, giúp giải độc, giảm cân và làm đẹp da cho người uống. Ô Long Chanh Leo thường được uống vào buổi chiều hoặc khi muốn thư giãn.',
                'trang_thai' => '1',
                'gia_ban' => '40.000',
                'gia_khuyen_mai'    => '36.000',
                'hinh_anh'    => 'https://bom.so/SBDIvS',
                'so_luong'  => '20',
            ],
            [
                'id_danh_muc'  => 1,
                'ten_san_pham' => 'Chanh Vàng Kim Quất',
                'slug_san_pham' => Str::slug('Chanh Vàng Kim Quất'),
                'mo_ta_ngan'    => 'là loại nước ép được làm từ chanh vàng và kim quất, có vị chua ngọt và mát lạnh..',
                'mo_ta_chi_tiet' => 'chứa nhiều vitamin C, giúp tăng cường hệ miễn dịch, chống cảm lạnh và giải nhiệt cho cơ thể. Chanh Vàng Kim Quất thường được uống vào mùa hè hoặc khi bị khát.',
                'trang_thai' => '1',
                'gia_ban' => '35.000',
                'gia_khuyen_mai'    => '31.500',
                'hinh_anh'    => 'https://bom.so/X54OvC',
                'so_luong'  => '20',
            ],
            [
                'id_danh_muc'  => 1,
                'ten_san_pham' => 'Cafe Americano',
                'slug_san_pham' => Str::slug('Cafe Americano'),
                'mo_ta_ngan'    => ' là loại cà phê được pha chế bằng cách thêm nước nóng vào espresso, có vị đắng và thơm.',
                'mo_ta_chi_tiet' => ' lượng caffeine cao, giúp tăng cường sự tỉnh táo và năng lượng cho người uống. Cafe Americano thường được uống vào buổi sáng hoặc khi cần làm việc lâu.',
                'trang_thai' => '1',
                'gia_ban' => '45.000',
                'gia_khuyen_mai'    => '40.500',
                'hinh_anh'    => 'https://bom.so/oUgJjs',
                'so_luong'  => '20',
            ],
            [
                'id_danh_muc'  => 2,
                'ten_san_pham' => 'Dây Dắt Yếm',
                'slug_san_pham' => Str::slug('Dây Dắt Yếm'),
                'mo_ta_ngan'    => 'là một loại dây dắt cho chó mèo, có thiết kế dạng yếm ôm gọn phần ngực của thú cưng.',
                'mo_ta_chi_tiet' => 'Dây dắt có yếm bọc ngực, giúp bảo vệ cổ và ngực của thú cưng khỏi bị tổn thương khi bị kéo. Dây dắt cũng có nhiều kích cỡ và màu sắc, giúp phù hợp với kích thước và sở thích của thú cưng.',
                'trang_thai' => '1',
                'gia_ban' => '65.000',
                'gia_khuyen_mai'    => '58.500',
                'hinh_anh'    => 'https://bom.so/qD225k',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 2,
                'ten_san_pham' => 'Dây Dắt Trợ Lực',
                'slug_san_pham' => Str::slug('Dây Dắt Trợ Lực'),
                'mo_ta_ngan'    => 'là một loại dây dắt cho chó, có thiết kế dạng yếm hoặc vòng cổ, kết hợp với một lò xo giảm lực',
                'mo_ta_chi_tiet' => 'Dây dắt có đệm lót, giúp giảm áp lực lên tay và cổ của bạn và thú cưng. Dây dắt cũng có khả năng co giãn, giúp điều chỉnh lực kéo của thú cưng một cách linh hoạt.',
                'trang_thai' => '1',
                'gia_ban' => '80.000',
                'gia_khuyen_mai'    => '72.000',
                'hinh_anh'    => 'https://bom.so/aLQBbj',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 2,
                'ten_san_pham' => 'Chuông/Lục Lạc',
                'slug_san_pham' => Str::slug('Chuông/Lục Lạc'),
                'mo_ta_ngan'    => 'là một loại phụ kiện được đeo trên cổ chó mèo, có tác dụng giúp chủ nhân dễ dàng xác định vị trí của thú cưng khi đi dạo hoặc chơi đùa',
                'mo_ta_chi_tiet' => ' Chuông có nhiều màu sắc và âm thanh khác nhau, giúp cho thú cưng không nhàm chán hoặc sợ hãi. Chuông cũng giúp tăng cường khả năng nghe và phản xạ của thú cưng.',
                'trang_thai' => '1',
                'gia_ban' => '10.000',
                'gia_khuyen_mai'    => '9.000',
                'hinh_anh'    => 'https://bom.so/N5R9mR',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 2,
                'ten_san_pham' => 'Áo kẻ kèm túi đeo chéo gấu Bear',
                'slug_san_pham' => Str::slug('Áo kẻ kèm túi đeo chéo gấu Bear'),
                'mo_ta_ngan'    => 'là một loại áo ba lỗ cho chó mèo, có thiết kế kẻ caro cùng với chiếc túi đeo đính kèm sau lưng đáng yêu',
                'mo_ta_chi_tiet' => 'Áo có túi đeo chéo hình gấu bông, giúp cho thú cưng có thể mang theo đồ chơi hoặc đồ ăn nhỏ. Áo cũng giúp tạo phong cách riêng biệt cho thú cưng.',
                'trang_thai' => '1',
                'gia_ban' => '110.000',
                'gia_khuyen_mai'    => '99.000',
                'hinh_anh'    => 'https://bom.so/OhVI1P',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 2,
                'ten_san_pham' => 'Áo 2 dây caro Baby',
                'slug_san_pham' => Str::slug('Áo 2 dây caro Baby'),
                'mo_ta_ngan'    => 'là một loại áo hai dây cho chó mèo, có thiết kế dạng 2 dây với kẻ caro cùng chất liệu mềm mại, êm ái, phù hợp cho cún nhỏ và vừa',
                'mo_ta_chi_tiet' => ' Áo có thiết kế hai dây, không gây bí hay rối cho thú cưng. Áo có họa tiết caro nhỏ, mang lại vẻ đẹp nhẹ nhàng và thanh lịch. Áo cũng giúp làm mát cho thú cưng vào những ngày nắng nóng.',
                'trang_thai' => '1',
                'gia_ban' => '55.000',
                'gia_khuyen_mai'    => '49.500',
                'hinh_anh'    => 'https://bom.so/1HzWQK',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 2,
                'ten_san_pham' => 'Áo cộc tay thỏ carrot',
                'slug_san_pham' => Str::slug('Áo cộc tay thỏ carrot'),
                'mo_ta_ngan'    => ' Áo có thiết kế ngắn tay, không gây nóng hay khó chịu cho thú cưng. Áo có hình thỏ và cà rốt, phù hợp với tính cách nghịch ngợm và đáng yêu của thú cưng. Áo cũng giữ ấm cho thú cưng vào những ngày se lạnh.',
                'mo_ta_chi_tiet' => 'chứa nhiều tinh dầu, giúp giảm stress, thư giãn và tăng cường trí nhớ cho người uống. Tứ Kỳ Xuân Latte thường được uống vào buổi sáng hoặc khi cần tập trung.',
                'trang_thai' => '1',
                'gia_ban' => '80.000',
                'gia_khuyen_mai'    => '72.000',
                'hinh_anh'    => 'https://bom.so/0FzCKY',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 2,
                'ten_san_pham' => 'Tinh dầu dưỡng lông SH Relax Pet Essential 80ml',
                'slug_san_pham' => Str::slug('Tinh dầu dưỡng lông SH Relax Pet Essential 80ml'),
                'mo_ta_ngan'    => 'là một sản phẩm giúp dưỡng lông, giảm rụng lông, giảm rối lông, giúp lông mềm mượt và óng ả cho chó mèo.',
                'mo_ta_chi_tiet' => 'Tinh dầu có thành phần thiên nhiên, không gây kích ứng da hoặc mắt cho thú cưng. Tinh dầu cũng có tác dụng làm dịu tâm trạng, giảm căng thẳng, và ngăn ngừa các bệnh về da và lông.',
                'trang_thai' => '1',
                'gia_ban' => '144.000',
                'gia_khuyen_mai'    => '129.600',
                'hinh_anh'    => 'https://bom.so/UpUD8z',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 2,
                'ten_san_pham' => 'Găng chải lông chó mèo',
                'slug_san_pham' => Str::slug('Găng chải lông chó mèo'),
                'mo_ta_ngan'    => 'là một loại dụng cụ chải lông cho chó mèo, có thiết kế dạng găng tay, có các gai mềm mại giúp loại bỏ lông rụng, lông chết, đồng thời massage da cho thú cưng.',
                'mo_ta_chi_tiet' => ' Găng tay có gai nhựa giúp loại bỏ các bụi bẩn, tạp chất, và lông rụng trên bề mặt lông. Găng tay cũng có tác dụng massage cho thú cưng, giúp kích thích tuần hoàn máu và làm dịu cơ bắp.',
                'trang_thai' => '1',
                'gia_ban' => '23.000',
                'gia_khuyen_mai'    => '20.700',
                'hinh_anh'    => 'https://bom.so/MMSnWf',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 2,
                'ten_san_pham' => 'Chuồng vải bông cho chó',
                'slug_san_pham' => Str::slug('Chuồng vải bông cho chó'),
                'mo_ta_ngan'    => 'là một loại chuồng cho chó được làm từ chất liệu vải bông, có thiết kế nhỏ gọn, tiện lợi, phù hợp để sử dụng trong nhà.',
                'mo_ta_chi_tiet' => ' Chuồng có thể gấp gọn và mang theo khi đi du lịch hoặc di chuyển. Chuồng cũng có thể giữ ấm cho chó vào mùa đông và ngăn chó bị côn trùng cắn.',
                'trang_thai' => '1',
                'gia_ban' => '500.000',
                'gia_khuyen_mai'    => '450.000',
                'hinh_anh'    => 'https://bom.so/eddkSX',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 3,
                'ten_san_pham' => 'Hạt Pedigree Puppy vị gà và trứng 400g',
                'slug_san_pham' => Str::slug('Hạt Pedigree Puppy vị gà và trứng 400g'),
                'mo_ta_ngan'    => 'là loại thức ăn khô cho chó con có vị gà và trứng, giàu protein và canxi, giúp tăng cường phát triển xương khớp và cơ bắp.',
                'mo_ta_chi_tiet' => 'Hạt Pedigree Puppy giúp chó con có xương khớp vững chắc, cơ bắp săn chắc và năng lượng dồi dào. Hạt Pedigree Puppy cũng giúp chó con ngăn ngừa bệnh loãng xương, suy dinh dưỡng và co cứng cơ.',
                'trang_thai' => '1',
                'gia_ban' => '57.000',
                'gia_khuyen_mai'    => '51.300',
                'hinh_anh'    => 'https://bom.so/7uEZf6',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 3,
                'ten_san_pham' => 'Thức ăn hạt Dog On Green 5kg – Protein 24%',
                'slug_san_pham' => Str::slug('Thức ăn hạt Dog On Green 5kg – Protein 24%'),
                'mo_ta_ngan'    => 'là loại thức ăn khô cho chó có vị rau xanh, giàu protein và vitamin, giúp tăng cường sức khỏe tổng thể và miễn dịch.',
                'mo_ta_chi_tiet' => 'Hạt Dog On Green giúp chó có cơ thể khỏe mạnh, da lông sáng bóng và hệ miễn dịch tốt. Thức ăn hạt Dog On Green cũng giúp chó ngăn ngừa bệnh thiếu vitamin, viêm da và ung thư.',
                'trang_thai' => '1',
                'gia_ban' => '370.0000',
                'gia_khuyen_mai'    => '333.000',
                'hinh_anh'    => 'https://bom.so/z2MTh8',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 3,
                'ten_san_pham' => 'Hạt Classic Pets Small Breed Dog Beef Flavour – 2kg',
                'slug_san_pham' => Str::slug('Hạt Classic Pets Small Breed Dog Beef Flavour – 2kg'),
                'mo_ta_ngan'    => 'là loại thức ăn khô cho chó nhỏ có vị thịt bò, giàu protein và chất xơ, giúp tăng cường răng miệng và tiêu hóa.',
                'mo_ta_chi_tiet' => 'Hạt Classic Pets Small Breed Dog giúp chó nhỏ có hàm răng chắc khỏe, hệ tiêu hóa tốt và phân ít mùi. Hạt Classic Pets Small Breed Dog cũng giúp chó nhỏ ngăn ngừa bệnh sâu răng, tiêu chảy và sán.',
                'trang_thai' => '1',
                'gia_ban' => '125.000',
                'gia_khuyen_mai'    => '112.500',
                'hinh_anh'    => 'https://bom.so/nKILdG',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 3,
                'ten_san_pham' => 'Pate Pedigree Puppy 130g cho chó con vị gà nấu sốt',
                'slug_san_pham' => Str::slug('Pate Pedigree Puppy 130g cho chó con vị gà nấu sốt'),
                'mo_ta_ngan'    => 'là loại thức ăn ướt cho chó con có vị gà nấu sốt, giàu protein và dầu cá, giúp tăng cường phát triển não bộ và lông.',
                'mo_ta_chi_tiet' => ' Pate Pedigree Puppy có công dụng là giúp chó con có trí thông minh cao, lông bóng mượt và hệ miễn dịch khỏe mạnh. Pate Pedigree Puppy cũng giúp chó con ngăn ngừa bệnh rối loạn não bộ, rụng lông và viêm da.',
                'trang_thai' => '1',
                'gia_ban' => '23.000',
                'gia_khuyen_mai'    => '20.700',
                'hinh_anh'    => 'https://bom.so/k1eD0F',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 3,
                'ten_san_pham' => 'Pate SmartHeart Adult cho chó lớn trên 1 tuổi gói 400g',
                'slug_san_pham' => Str::slug('Pate SmartHeart Adult cho chó lớn trên 1 tuổi gói 400g'),
                'mo_ta_ngan'    => 'là loại thức ăn ướt cho chó lớn có vị thịt bò và gan, giàu protein và sắt, giúp tăng cường cơ bắp và máu.',
                'mo_ta_chi_tiet' => 'Pate SmartHeart Adult có công dụng là giúp chó lớn có sức khỏe tốt, cơ thể săn chắc và da lông khỏe mạnh. Pate SmartHeart Adult cũng giúp chó lớn ngăn ngừa bệnh thiếu máu, suy nhược cơ thể và viêm nhiễm.',
                'trang_thai' => '1',
                'gia_ban' => '29.000',
                'gia_khuyen_mai'    => '26.100',
                'hinh_anh'    => 'https://bom.so/jZkCT0',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 3,
                'ten_san_pham' => 'Sữa bột AG-Science cho chó mèo hộp 250g',
                'slug_san_pham' => Str::slug('Sữa bột AG-Science cho chó mèo hộp 250g'),
                'mo_ta_ngan'    => 'là loại thức ăn ướt cho chó lớn có vị thịt bò và gan, giàu protein và sắt, giúp tăng cường cơ bắp và máu.',
                'mo_ta_chi_tiet' => ' Sữa bột AG-Science có công dụng là giúp chó mèo có cân nặng phù hợp, lông óng ả và miễn dịch tốt. Sữa bột AG-Science cũng giúp chó mèo ngăn ngừa bệnh thiếu máu, suy dinh dưỡng và nhiễm trùng.',
                'trang_thai' => '1',
                'gia_ban' => '130.000',
                'gia_khuyen_mai'    => '117.000',
                'hinh_anh'    => ' https://bom.so/Hzxm60',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 3,
                'ten_san_pham' => 'Sữa Miu Milk cho mèo gói 100g',
                'slug_san_pham' => Str::slug('Sữa Miu Milk cho mèo gói 100g'),
                'mo_ta_ngan'    => ' là loại sữa bột cho chó mèo có vị sữa bò, giàu protein và chất béo, giúp bổ sung dinh dưỡng và tăng cường sức đề kháng.',
                'mo_ta_chi_tiet' => ' Sữa Miu Milk có công dụng là giúp mèo có răng miệng chắc khỏe, da dẻ sáng bóng và năng lượng dồi dào. Sữa Miu Milk cũng giúp mèo ngăn ngừa bệnh sâu răng, rối loạn tiêu hóa và suy nhược cơ thể.',
                'trang_thai' => '1',
                'gia_ban' => '55.000',
                'gia_khuyen_mai'    => '49.500',
                'hinh_anh'    => 'https://bom.so/m7mJcL',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 3,
                'ten_san_pham' => 'Pate Meow Mix cho mèo làm từ thịt bò, gà và cá ngừ hộp 78g',
                'slug_san_pham' => Str::slug('Pate Meow Mix cho mèo làm từ thịt bò, gà và cá ngừ hộp 78g'),
                'mo_ta_ngan'    => 'là loại thức ăn ướt cho mèo có vị hỗn hợp thịt bò, gà và cá ngừ, giàu vitamin và khoáng chất.',
                'mo_ta_chi_tiet' => ' Pate Meow Mix có công dụng là giúp mèo có sức đề kháng cao, cơ bắp săn chắc và xương khớp vững chắc. Pate Meow Mix cũng giúp mèo ngăn ngừa bệnh thiếu máu, suy dinh dưỡng và loãng xương.',
                'trang_thai' => '1',
                'gia_ban' => '26.000',
                'gia_khuyen_mai'    => '23.400',
                'hinh_anh'    => 'https://bom.so/tvm28E',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 3,
                'ten_san_pham' => 'Pate Snappy Tom gói 85g',
                'slug_san_pham' => Str::slug('Pate Snappy Tom gói 85g'),
                'mo_ta_ngan'    => 'là loại thức ăn ướt cho mèo có vị cá ngừ và cá hồi, giàu omega-3 và omega-6.',
                'mo_ta_chi_tiet' => 'Pate Snappy Tom có công dụng là giúp mèo có não bộ phát triển, tim mạch khỏe mạnh và lông óng ả. Pate Snappy Tom cũng giúp mèo ngăn ngừa bệnh viêm da, viêm khớp và ung thư.',
                'trang_thai' => '1',
                'gia_ban' => '25.000',
                'gia_khuyen_mai'    => '22.500',
                'hinh_anh'    => 'https://bom.so/ofZK4m',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 3,
                'ten_san_pham' => 'Pate Cherman cho mèo gói 85g',
                'slug_san_pham' => Str::slug('Pate Cherman cho mèo gói 85g'),
                'mo_ta_ngan'    => ' là loại thức ăn ướt cho mèo có vị thịt gà và cá, giàu protein và dinh dưỡng.',
                'mo_ta_chi_tiet' => ' Pate Cherman có công dụng là giúp mèo có lông bóng mượt, da khỏe mạnh và hệ tiêu hóa tốt. Pate Cherman cũng giúp mèo ngăn ngừa bệnh nhiễm trùng, tiêu chảy và sán.',
                'trang_thai' => '1',
                'gia_ban' => '18.000',
                'gia_khuyen_mai'    => '16.200',
                'hinh_anh'    => 'https://bom.so/a1srqN',
                'so_luong'  => '10',
            ],
            [
                'id_danh_muc'  => 4,
                'ten_san_pham' => 'Vịt mỏ cam chíp chíp',
                'slug_san_pham' => Str::slug('Vịt mỏ cam chíp chíp'),
                'mo_ta_ngan'    => ' là một loại đồ chơi thú cưng được làm từ chất liệu cao su mềm, có hình dáng giống một chú vịt vàng với mỏ màu cam, khi bóp sẽ phát ra tiếng kêu "chip chip".',
                'mo_ta_chi_tiet' => 'Vịt mỏ cam chíp chíp có công dụng là giúp chó giải trí, tăng cường khả năng nghe và phản ứng. Vịt mỏ cam chíp chíp cũng giúp chó rèn luyện khả năng nhai và cắn.',
                'trang_thai' => '1',
                'gia_ban' => '55.000',
                'gia_khuyen_mai'    => '49.500',
                'hinh_anh'    => 'https://bom.so/U4gkSD',
                'so_luong'  => '5',
            ],
            [
                'id_danh_muc'  => 4,
                'ten_san_pham' => 'Bóng cao su hình dấu chân cún',
                'slug_san_pham' => Str::slug('Bóng cao su hình dấu chân cún'),
                'mo_ta_ngan'    => ' là một loại đồ chơi thú cưng được làm từ chất liệu cao su mềm, có hình dáng giống một dấu chân cún, khi lăn sẽ phát ra tiếng kêu vui nhộn.',
                'mo_ta_chi_tiet' => 'Bóng cao su hình dấu chân cún có công dụng là giúp chó thỏa mãn bản năng săn bắt và vui chơi, tăng cường sức khỏe tim mạch và cơ bắp. Bóng cao su hình dấu chân cún cũng giúp tăng sự gắn kết giữa bạn và chó khi ném và bắt bóng.',
                'trang_thai' => '1',
                'gia_ban' => '15.000',
                'gia_khuyen_mai'    => '13.500',
                'hinh_anh'    => 'https://bom.so/ZrNaQN',
                'so_luong'  => '5',
            ],
            [
                'id_danh_muc'  => 4,
                'ten_san_pham' => 'Bàn cào tròn 36x10cm',
                'slug_san_pham' => Str::slug('Bàn cào tròn 36x10cm'),
                'mo_ta_ngan'    => ' là một loại bàn cào cho mèo, có thiết kế dạng tròn, kích thước nhỏ gọn, phù hợp với các chú mèo nhỏ hoặc mèo con.',
                'mo_ta_chi_tiet' => ' Bàn cào tròn 36x10cm có công dụng là giúp mèo duy trì móng khỏe mạnh, ngăn ngừa móng gây hại cho đồ đạc và người. Bàn cào tròn 36x10cm cũng giúp mèo phát tiết hormone hạnh phúc khi cào.',
                'trang_thai' => '1',
                'gia_ban' => '140.000',
                'gia_khuyen_mai'    => '126.000',
                'hinh_anh'    => 'https://bom.so/YCcfIS',
                'so_luong'  => '5',
            ],
            [
                'id_danh_muc'  => 4,
                'ten_san_pham' => 'Mèo leo hình vuông 2 tầng',
                'slug_san_pham' => Str::slug('Mèo leo hình vuông 2 tầng'),
                'mo_ta_ngan'    => ' là một loại bàn cào cho mèo, có thiết kế dạng tròn, kích thước nhỏ gọn, phù hợp với các chú mèo nhỏ hoặc mèo con.',
                'mo_ta_chi_tiet' => ' Mèo leo hình vuông 2 tầng có công dụng là giúp mèo thỏa mãn bản năng thám hiểm, tăng cường sức khỏe cơ thể và trí tuệ. Mèo leo hình vuông 2 tầng cũng giúp mèo có không gian riêng và an toàn.',
                'trang_thai' => '1',
                'gia_ban' => '165.000',
                'gia_khuyen_mai'    => '148.500',
                'hinh_anh'    => 'https://bom.so/SQd0oR',
                'so_luong'  => '5',
            ],
            [
                'id_danh_muc'  => 4,
                'ten_san_pham' => 'Bóng hàm răng',
                'slug_san_pham' => Str::slug('Bóng hàm răng'),
                'mo_ta_ngan'    => 'là một loại đồ chơi cho thú cưng, có hình dáng giống một quả bóng, được làm từ chất liệu cao su hoặc nhựa mềm, có tác dụng giúp thú cưng nhai, cắn, giúp giảm thiểu tình trạng thú cưng cắn phá đồ đạc trong nhà.',
                'mo_ta_chi_tiet' => 'Bóng hàm răng có công dụng là giúp chó giảm stress, tăng cường sức khỏe răng miệng và ngăn ngừa bệnh về nướu. Bóng hàm răng cũng giúp chó rèn luyện khả năng nhai và cắn.',
                'trang_thai' => '1',
                'gia_ban' => '14.000',
                'gia_khuyen_mai'    => '12.600',
                'hinh_anh'    => 'https://bom.so/HxpQLL',
                'so_luong'  => '5',
            ],
            [
                'id_danh_muc'  => 4,
                'ten_san_pham' => 'Cần câu mèo',
                'slug_san_pham' => Str::slug('Cần câu mèo'),
                'mo_ta_ngan'    => 'là một loại đồ chơi cho mèo, có thiết kế dạng cần câu, có gắn lông vũ hoặc đồ chơi nhỏ, được sử dụng để dụ mèo chơi đùa.',
                'mo_ta_chi_tiet' => 'Cần câu mèo có công dụng là giúp mèo giải trí, tăng cường sự linh hoạt và khả năng phản xạ của mèo. Cần câu mèo cũng giúp tăng sự gắn kết giữa bạn và mèo khi chơi cùng nhau.',
                'trang_thai' => '1',
                'gia_ban' => '35.000',
                'gia_khuyen_mai'    => '31.500',
                'hinh_anh'    => 'https://bom.so/JY1b43',
                'so_luong'  => '5',
            ],
        ]);
    }
}
